version: "2"
services:
 web:
  build: image
  command: sh bin/run-test
  working_dir: /lesson1
  volumes:
   - ..:/lesson1
  links:
   - mysql
   - redis
 mysql:
  image: mysql:5
  environment:
   MYSQL_DATABASE: lesson1
   MYSQL_ROOT_PASSWORD: dev
 redis:
  image: redis
  ports:
   - "6379:6379"
