"""empty message

Revision ID: 47a82dc799a6
Revises: 46287ddde258
Create Date: 2018-06-22 06:02:34.602897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47a82dc799a6'
down_revision = '46287ddde258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_charset',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('something', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_charset')
    # ### end Alembic commands ###
