"""empty message

Revision ID: 498d0f51fe31
Revises: 68ac6fb1c086
Create Date: 2018-06-25 12:52:29.850421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '498d0f51fe31'
down_revision = '68ac6fb1c086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_closure',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('depth', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_department_tree_d', 'department_closure', ['department_id'], unique=False)
    op.create_index('idx_department_tree_p', 'department_closure', ['parent_id'], unique=False)
    op.drop_index('idx_department_tree_d', table_name='department_tree')
    op.drop_index('idx_department_tree_p', table_name='department_tree')
    op.drop_table('department_tree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_tree',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('depth', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_department_tree_p', 'department_tree', ['parent_id'], unique=False)
    op.create_index('idx_department_tree_d', 'department_tree', ['department_id'], unique=False)
    op.drop_index('idx_department_tree_p', table_name='department_closure')
    op.drop_index('idx_department_tree_d', table_name='department_closure')
    op.drop_table('department_closure')
    # ### end Alembic commands ###
