"""empty message

Revision ID: 68ac6fb1c086
Revises: 9f2abdd7a490
Create Date: 2018-06-25 12:49:54.650669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68ac6fb1c086'
down_revision = '9f2abdd7a490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_tree',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('depth', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_department_tree_d', 'department_tree', ['department_id'], unique=False)
    op.create_index('idx_department_tree_p', 'department_tree', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_department_tree_p', table_name='department_tree')
    op.drop_index('idx_department_tree_d', table_name='department_tree')
    op.drop_table('department_tree')
    # ### end Alembic commands ###
