"""empty message

Revision ID: 9f2abdd7a490
Revises: bf6d916ec705
Create Date: 2018-06-25 12:33:02.465152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f2abdd7a490'
down_revision = 'bf6d916ec705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_permission',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_leader_permission_d', 'leader_permission', ['department_id'], unique=False)
    op.drop_table('employee_department')
    op.create_index('idx_department_permission_d', 'department_permission', ['department_id'], unique=False)
    op.drop_column('department_permission', 'leader_only')
    op.add_column('department_tree', sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.add_column('department_tree', sa.Column('depth', mysql.BIGINT(unsigned=True), nullable=False))
    op.add_column('department_tree', sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.create_index('idx_department_tree_d', 'department_tree', ['department_id'], unique=False)
    op.create_index('idx_department_tree_p', 'department_tree', ['parent_id'], unique=False)
    op.drop_column('department_tree', 'parent_path')
    op.add_column('employee', sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'department_id')
    op.add_column('department_tree', sa.Column('parent_path', mysql.VARCHAR(length=128), nullable=False))
    op.drop_index('idx_department_tree_p', table_name='department_tree')
    op.drop_index('idx_department_tree_d', table_name='department_tree')
    op.drop_column('department_tree', 'parent_id')
    op.drop_column('department_tree', 'depth')
    op.drop_column('department_tree', 'department_id')
    op.add_column('department_permission', sa.Column('leader_only', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_index('idx_department_permission_d', table_name='department_permission')
    op.create_table('employee_department',
    sa.Column('employee_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('idx_leader_permission_d', table_name='leader_permission')
    op.drop_table('leader_permission')
    # ### end Alembic commands ###
